all: 
	g++ roadtrip-infinity.cpp -o roadtrip-infinity
	gcc roadtrip-peters.c -o roadtrip-peters
	g++ traintrips-dimos.cpp -o traintrips-dimos
	g++ roadtrip.cpp -o roadtrip
	g++ traintrips.cpp -o traintrips
